# Generated by Django 5.0.6 on 2024-06-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(max_length=30),
        ),
    ]
