# Generated by Django 5.0.6 on 2024-06-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
