# Generated by Django 5.0.6 on 2024-06-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.FileField(null=True, upload_to='products/'),
        ),
    ]
