# Generated by Django 5.0.6 on 2024-06-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_catergory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
    ]
