# Generated by Django 5.0.6 on 2024-06-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(max_length=100),
        ),
    ]
